#!/bin/bash

printmsg () {
        echo -e "\033[32m$1\033[0m"
}

errormsg () {
        echo -e "\033[31m$1 \033[0m" 1>&2
}

[ -x /usr/local/bin/vault ] && {
	sudo cp /usr/local/bin/vault /usr/local/bin/vault.orig.$(date +%s)
} 

sudo cp vault /usr/local/bin/

/usr/local/bin/vault init

